#!/bin/bash -eux

ARGS=(
 # Many people don't suspect it, but Emacs typically got server and client part. 
 # As opposed to daemon (i.e. default emacs command), spawning a client (e.g. emacsclient)
 # is extremely fast, a matter of creating a window, but that means you have to deal
 # with having a daemon running.

 # This trick gives you best of two worlds: if there is an Emacs daemon running,
 # it just connects to it
 # Otherwise, it spawns a daemon first and then connects to it.
 # Without this setting if you don't have a daemon, the command would fail.
 -a ''

 # spawn new GUI window, otherwise it tries to launch client in terminal
 --create-frame 
 -F "'(fullscreen . maximized)"

 # process rest of arguments as elisp code
 -e
  # bring focus to the window
 '(select-frame-set-input-focus (selected-frame))'
)


exec emacsclient "${ARGS[@]}" \
                 "$@"          # pass through whatever else you are trying to run
                                                 

# TODO maximize?
# TODO wtf was that?
#  # "(delete-other-windows)" # "(spacemacs/home)"
